# Generated by Django 3.2.8 on 2022-07-09 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220709_1757'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
