# Generated by Django 3.2.8 on 2022-07-09 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('First_name', models.CharField(blank=True, max_length=50, null=True)),
                ('Last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('Phone_No', models.IntegerField(blank=True, null=True, unique=True)),
                ('Credit_card_No', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('User_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
