# Generated by Django 3.2.8 on 2022-07-14 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20220709_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='Flight_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.flights'),
        ),
    ]
