# Generated by Django 3.2.8 on 2022-07-16 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20220716_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airline_companies',
            old_name='country_id',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='airline_companies',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='flights',
            old_name='airline_Company_id',
            new_name='airline_company_id',
        ),
        migrations.RenameField(
            model_name='flights',
            old_name='destenation_Country_id',
            new_name='destenation_country_id',
        ),
        migrations.RenameField(
            model_name='flights',
            old_name='origin_Country_id',
            new_name='origin_country_id',
        ),
    ]
