# Generated by Django 3.2.8 on 2022-07-16 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20220716_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airline_companies',
            old_name='user',
            new_name='user_checker',
        ),
    ]
