# Generated by Django 3.2.8 on 2022-07-16 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_user_airline_companies_user_checker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airline_companies',
            old_name='user_checker',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='flights',
            old_name='airline_company_id',
            new_name='airline_company',
        ),
        migrations.RenameField(
            model_name='flights',
            old_name='destenation_country_id',
            new_name='destenation_country',
        ),
        migrations.RenameField(
            model_name='flights',
            old_name='origin_country_id',
            new_name='origin_country',
        ),
        migrations.RenameField(
            model_name='tickets',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='flight_id',
        ),
        migrations.AddField(
            model_name='tickets',
            name='flight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.flights'),
        ),
    ]
