# Generated by Django 3.2.8 on 2022-07-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20220716_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='flag',
            field=models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to=''),
        ),
    ]
