# Generated by Django 3.2.8 on 2022-07-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_countries_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='flag',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
