# Generated by Django 3.2.8 on 2022-07-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_customers_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='departure_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='flights',
            name='landing_time',
            field=models.DateTimeField(),
        ),
    ]
