# Generated by Django 3.2.8 on 2022-07-23 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20220723_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='destenation_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destenation_country', to='base.countries'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='origin_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_country', to='base.countries'),
        ),
    ]
