# Generated by Django 3.2.8 on 2022-09-01 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0017_alter_countries_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline_companies',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.countries'),
        ),
        migrations.AlterField(
            model_name='airline_companies',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flights',
            name='airline_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.airline_companies'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='destenation_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destenation_country', to='base.countries'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='origin_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_country', to='base.countries'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.customers'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='flight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.flights'),
        ),
    ]
